# .goreleaser.yaml
project_name: your-cli-tool-name

builds:
  - main: ./cmd/your-cli
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: your-github-username
    name: your-repo-name

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
